export const API_BASE = import.meta.env.VITE_API_URL ?? 'https://api.tissuepro.id'

export const API_URLS = {
  public: {
    products:      `${API_BASE}/api/public/products`,
    pipeline:      `${API_BASE}/api/public/pipeline`,
    caseStudies:   `${API_BASE}/api/public/case-studies`,
    areas:         `${API_BASE}/api/public/application-areas`,
    inquirySubmit: `${API_BASE}/api/submit/inquiry`,
  },
  auth: {
    login:    `${API_BASE}/api/auth/login`,
    register: `${API_BASE}/api/auth/register`,
    refresh:  `${API_BASE}/api/auth/refresh`,
    password: `${API_BASE}/api/auth/me/password`,
  },
  users: {
    me:           `${API_BASE}/api/users/me`,
    profile:      `${API_BASE}/api/users/profile`,
    subscription: `${API_BASE}/api/users/me/subscription`,
    all:          `${API_BASE}/api/users`,
    stats:        `${API_BASE}/api/users/stats`,
  },
  articles: {
    public: `${API_BASE}/api/articles`,
    admin:  `${API_BASE}/api/articles/admin/all`,
  },
  tickets: {
    create: `${API_BASE}/api/tickets`,
    mine:   `${API_BASE}/api/tickets/mine`,
    admin:  `${API_BASE}/api/tickets/admin/all`,
  },
  payment: {
    subscribe: `${API_BASE}/api/payment/subscribe`,
    history:   `${API_BASE}/api/payment/history`,
    admin:     `${API_BASE}/api/payment/admin/all`,
  },
  cart: {
    get:        `${API_BASE}/api/cart`,
    addItem:    `${API_BASE}/api/cart/items`,
    updateItem: (id: string) => `${API_BASE}/api/cart/items/${id}`,
    deleteItem: (id: string) => `${API_BASE}/api/cart/items/${id}`,
    clear:      `${API_BASE}/api/cart`,
  },
  orders: {
    create:         `${API_BASE}/api/orders`,
    list:           `${API_BASE}/api/orders`,
    detail:         (id: string) => `${API_BASE}/api/orders/${id}`,
    initiatePayment:`${API_BASE}/api/payments/initiate`,
  },
  cms: {
    dashboardStats:  `${API_BASE}/api/cms/dashboard/stats`,
    inquiries:       `${API_BASE}/api/cms/inquiries`,
    inquiry:         (id: string) => `${API_BASE}/api/cms/inquiries/${id}`,
    products:        `${API_BASE}/api/cms/products`,
    product:         (id: string) => `${API_BASE}/api/cms/products/${id}`,
    areas:           `${API_BASE}/api/cms/application-areas`,
    area:            (id: string) => `${API_BASE}/api/cms/application-areas/${id}`,
    caseStudies:     `${API_BASE}/api/cms/case-studies`,
    caseStudy:       (id: string) => `${API_BASE}/api/cms/case-studies/${id}`,
    pipeline:        `${API_BASE}/api/cms/pipeline`,
    pipelineItem:    (id: string) => `${API_BASE}/api/cms/pipeline/${id}`,
    documents:       `${API_BASE}/api/cms/documents`,
    document:        (id: string) => `${API_BASE}/api/cms/documents/${id}`,
    cmsArticles:     `${API_BASE}/api/cms/articles`,
    cmsArticle:      (id: string) => `${API_BASE}/api/cms/articles/${id}`,
    pageSettings:    `${API_BASE}/api/cms/page-settings`,
    generalSettings: `${API_BASE}/api/cms/general-settings`,
    adminUsers:      `${API_BASE}/api/cms/admin-users`,
    adminUser:       (id: string) => `${API_BASE}/api/cms/admin-users/${id}`,
    orders:          `${API_BASE}/api/cms/orders`,
    order:           (id: string) => `${API_BASE}/api/cms/orders/${id}`,
    orderStatus:     (id: string) => `${API_BASE}/api/cms/orders/${id}/status`,
    inquirySubmit:   `${API_BASE}/api/submit/inquiry`, // same endpoint as public.inquirySubmit — kept for CMS backward compat
    mediaUpload:     `${API_BASE}/api/cms/media/upload`,
    mediaDelete:     (path: string) => `${API_BASE}/api/cms/media/${encodeURIComponent(path)}`,
  },
}
